force_sensor_topic: "/optoforce_0"
controller_state: "/left_arm_controller/state"
joint_goal: "/left_arm_controller/follow_joint_trajectory/goal"
joint_result: "/left_arm_controller/follow_joint_trajectory/result"
trajectory_planned: "/trajectory_planned"
planning_group: "left_arm"
arm_prefix: "left_arm_"
maxJointErrorTollerance: 0.05
useSim: 1;
min_update_rate: 20
