force_sensor_topic: "/optoforce_0"
controller_state: "/arm_controller/joint_states"
joint_goal: "/arm_controller/follow_joint_trajectory/goal"
joint_result: "/arm_controller/follow_joint_trajectory/result"
trajectory_planned: "/trajectory_planned"
planning_group: "left_arm"
arm_prefix: "left_arm_"
maxJointErrorTollerance: 0.01
useSim: 0
min_update_rate: 20
